const Agent_Lists = [
  {
    id: "1",
    src: require("@/assets/img/balcony.jpg"),
    avatar: require("@/assets/img/25.jpg"),
    location: "41-43 Tung Street",
    area: "SA 214 sq.ft. / GA 320 sq.ft.",
    rooms: "Studio",
    bathroom: "1",
    price: "HK$5,180,000",
    ref: "22917",
  },
  {
    id: "2",
    src: require("@/assets/img/bedroom.jpeg"),
    avatar: require("@/assets/img/54.jpg"),
    location: "Ying Pont Building",
    area: "SA 214 sq.ft. / GA 320 sq.ft.",
    rooms: "Studio",
    bathroom: "1",
    price: "HK$5,180,000",
    ref: "22917",
  },
  {
    id: "3",
    src: require("@/assets/img/living-space.jpg"),
    avatar: require("@/assets/img/55.jpg"),
    location: "Hongway Garden",
    area: "SA 214 sq.ft. / GA 320 sq.ft.",
    rooms: "Studio",
    bathroom: "1",
    price: "HK$5,180,000",
    ref: "22917",
  },
  {
    id: "4",
    src: require("@/assets/img/living-space2.jpg"),
    avatar: require("@/assets/img/58.jpg"),
    location: "Rich View Terrace",
    area: "SA 214 sq.ft. / GA 320 sq.ft.",
    rooms: "Studio",
    bathroom: "1",
    price: "HK$5,180,000",
    ref: "22917",
  },
  {
    id: "5",
    src: require("@/assets/img/living.jpg"),
    avatar: require("@/assets/img/60.jpeg"),
    location: "Bohemian House",
    area: "SA 214 sq.ft. / GA 320 sq.ft.",
    rooms: "Studio",
    bathroom: "2",
    price: "HK$5,180,000",
    ref: "22917",
  },
  {
    id: "6",
    src: require("@/assets/img/view-01.jpg"),
    avatar: require("@/assets/img/64.jpg"),
    location: "6-12 Crown Terrace",
    area: "SA 214 sq.ft. / GA 320 sq.ft.",
    rooms: "Studio",
    bathroom: "1",
    price: "HK$5,180,000",
    ref: "22917",
  },
  {
    id: "7",
    src: require("@/assets/img/roof.jpg"),
    avatar: require("@/assets/img/66.jpg"),
    location: "7&9 Shin Hing Street",
    area: "SA 214 sq.ft. / GA 320 sq.ft.",
    rooms: "Studio",
    bathroom: "3",
    price: "HK$5,180,000",
    ref: "22917",
  },
];
export { Agent_Lists };
